import type { TemplateProps } from "./Template";

export function getDefaultModernTemplateProps(): Pick<TemplateProps, "lead" | "config"> {
  return {
    lead: {
      templateId: "modern",
      niche: "plumber",
      companyName: "MJ plumber and heating",
      location: "London",
      phone: "447778997257",
      email: "imranalfred@hotmail.com",
      contactMethod: "call",
      ctaText: "Get a Free Quote",
      primaryColor: "#112D4E",
      secondaryColor: "#3F72AF",
      accentColor: "#DBE2EF",
      logoUrl: "",
      teamPhotoUrl: "",
      yearsInBusiness: 20,
      openingHours: "Mon - Fri: 8am - 6pm",
      aboutText: "Fast response plumbing & heating across London. Clear pricing, tidy work, and straight answers.",
      accreditations: ["Fully Insured"],
      servicesOffered: ["general-plumbing", "leak-repair", "boiler-repair", "central-heating", "drain-unblocking", "emergency-plumbing"],
      customServices: [],
      serviceDescriptions: {
        "general-plumbing": "Practical repairs and replacements—pipes, fittings and valves done properly.",
        "leak-repair": "Trace the leak, fix the cause, and leave it tidy.",
        "boiler-repair": "Clear fault finding and sensible repair options.",
        "central-heating": "Radiators, valves, balancing and efficiency improvements.",
        "drain-unblocking": "Blocked sinks and drains cleared quickly with minimal mess.",
        "emergency-plumbing": "Urgent call-outs for active leaks and bursts to prevent damage.",
      },
      serviceImageRefs: {},
      recentProjects: [],
      customReviews: [],
      serviceAreas: ["London", "South London", "Surrey"],
      emergencyAvailable: true,
      showPricing: false,
      aboutFacts: { familyRun: true, local: true, established: true },
      upsells: [],
    },
    config: {
      id: "plumber",
      tradeSingular: "Plumber",
      tradePlural: "Plumbing & Heating",
      heroBadge: "Trusted Local Plumbing & Heating",
      heroTitle: "Plumbing & heating in your area",
      heroSubtitle: "Leaks, boilers, central heating, blocked drains, and emergency call-outs.",
      heroImages: ["hero.webp"],
      bottomCtaImage: "hero.webp",
      servicesHeading: "Plumbing & Heating Services",
      services: [
        { title: "General Plumbing", description: "Repairs and replacements done properly.", imageFilename: "plumbingwork.webp" },
        { title: "Boiler Repairs", description: "Fault finding and heating restoration.", imageFilename: "boilerinstallation.webp" },
      ],
      projects: [{ title: "Emergency Leak Repair", summary: "Leak stopped fast with tidy pipework repair.", img: "emergencywork.webp" }],
    },
  };
}
