import type { LeadPreviewState } from "@/lib/leadSchema";

/**
 * Baked-in lead data for this client site.
 * Generated by the VF Web Design exporter — do not edit the shape,
 * but you CAN tweak individual values (text, colors, etc.).
 */
export const lead: LeadPreviewState = {
  "templateId": "modern",
  "niche": "plumber",
  "companyName": "MJ plumber and heating",
  "location": "London",
  "phone": "447778997257",
  "email": "imranalfred@hotmail.com",
  "contactMethod": "call",
  "ctaText": "Get a Free Quote",
  "primaryColor": "#112D4E",
  "secondaryColor": "#3F72AF",
  "accentColor": "#DBE2EF",
  "logoUrl": "/Generated%20Image%20February%2027,%202026%20-%2012_16PM.jpg.jpeg",
  "teamPhotoUrl": "/Generated%20Image%20February%2026,%202026%20-%2011_54AM.jpg.jpeg",
  "aboutText": "Fast response plumbing & heating. Serving London and surrounding areas.",
  "accreditations": [],
  "servicesOffered": [
    "emergency-plumbing",
    "leak-repair",
    "boiler-repair",
    "central-heating",
    "drain-unblocking",
    "general-plumbing"
  ],
  "customServices": [],
  "serviceDescriptions": {},
  "serviceImageRefs": {
    "emergency-plumbing": "/Generated%20Image%20February%2026,%202026%20-%2012_50PM.jpg.jpeg",
    "leak-repair": "/leak-repair.png",
    "boiler-repair": "/boiler-repair.png",
    "central-heating": "/Generated%20Image%20February%2026,%202026%20-%201_05PM.jpg.jpeg",
    "drain-unblocking": "/Generated%20Image%20February%2026,%202026%20-%201_07PM.jpg.jpeg",
    "general-plumbing": "/Generated%20Image%20February%2026,%202026%20-%201_09PM.jpg.jpeg"
  },
  "recentProjects": [
    {
      "title": "Leak Repairs",
      "location": "London",
      "summary": "Leaks traced and fixed properly — pipes, joints, valves and fittings.",
      "imageRef": "/leak-repair.png"
    },
    {
      "title": "Boiler Repairs",
      "location": "London",
      "summary": "Clear fault finding, repairs and safety checks to get your heating back on.",
      "imageRef": "/boiler-repair.png"
    },
    {
      "title": "Drain Unblocking",
      "location": "London",
      "summary": "Blocked sinks and drains cleared quickly with minimal mess.",
      "imageRef": "/Generated%20Image%20February%2026,%202026%20-%201_07PM.jpg.jpeg"
    }
  ],
  "customReviews": [],
  "serviceAreas": [],
  "emergencyAvailable": false,
  "showPricing": false,
  "aboutFacts": {
    "familyRun": false,
    "local": false,
    "established": false
  },
  "upsells": []
};
